# Generated by Django 3.2.9 on 2021-12-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockManageModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('on_sale', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
