# Generated by Django 3.2.9 on 2021-12-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bought_at', models.DateTimeField()),
                ('staff_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('bought_count', models.IntegerField(default=0)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.purchasemodel')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.stockmanagemodel')),
            ],
        ),
    ]
